# fuente https://hub.docker.com/_/postgres
version: '3.9'

services: 
  postgres:
    #usamos la ultima imegn con latest y que siempre se reinicie
    image: postgres:latest
    restart: always
    
    # pasaremos ahora las variables del otro lado no javam osea para la BD, pero deben ser iguales
    environment:
      POSTGRESS_USER: ${SPRING_DATASOURCE_USARNAME}
      POSTGRESS_PASWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRESS_DB: ${SPRING_DATASOURCE_DB}
    
    ports:
      # asigno el 5432 al 5342 del java
      - 5432:5432
    volumes:
      # se generara una carpeta de la BD en nuestra carpeta
      - ./postgres:/var/lib/postgesql/data
